# Generated by Django 5.2.1 on 2025-06-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBoss', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='用户名'),
        ),
    ]
